add settings
Shushikian/ice-cream_team-project pull request #1
Opened 2022-04-02 18:50 UTC by zenoviyfil

added settings from test project to run and install npm ci. DID NOT touch our files

2022-04-02 22:23 UTC, Vitaliy-goIT commented on src/partials/header-hero.html
> +            <li class="header__nav__item"><a class="header__nav__link link" href="#">Home</a></li>
думаю что принципы БЭМ не соблюдены... не может быть блок__элемент__элемент, я бы заменил 
`header__nav__item`  на `header__nav-item`;
`header__nav__link`  на `header__nav-link`    и т. д.

2022-04-02 22:25 UTC, Vitaliy-goIT commented on src/partials/header-hero.html
> +        <button class="btn-header btn-light" type="button">Buy now
а тут модификаторы должны быть `btn--light`...

2022-04-02 22:27 UTC, Vitaliy-goIT commented on src/partials/header-hero.html
> +    <div class="hero-container">
а контейнер просто `class="container"` ведь он у нас всех общий...

2022-04-02 22:28 UTC, Vitaliy-goIT commented on src/partials/header-hero.html
> +            <li class="header__nav__item"><a class="header__nav__link link" href="#">Home</a></li>
сорян что свои 5ть копеек суда сунул)

2022-04-03 05:02 UTC, zenoviyfil commented on src/partials/header-hero.html
> +            <li class="header__nav__item"><a class="header__nav__link link" href="#">Home</a></li>
погоджуюсь

2022-04-03 05:02 UTC, zenoviyfil commented on src/partials/header-hero.html
> +        <button class="btn-header btn-light" type="button">Buy now
виправлю

2022-04-03 05:05 UTC, zenoviyfil commented on src/partials/header-hero.html
> +    <div class="hero-container">
не згідний, стилі контейнерів прописані помилково і контент не стає куда треба. Також мабуть я цього не зустрічав але я немаю жодного розуміння як поводитись із container-desk у variables, це ж виходить просто секція... нашо, куда вставляти, а на таблетку і мобілку тіпа іншу секцію робити? Лишній код получається. я завжди робив 3 контейнера з різними адаптаціями через @media. Підкажи як тут вестись тому що я загубився у цьому.

2022-04-03 05:10 UTC, zenoviyfil commented on src/partials/header-hero.html
> +        <button class="btn-header btn-light" type="button">Buy now
виправив, тепер поломались стилі кнопок, все таки не модифікатор а клас мабуть

2022-04-03 10:32 UTC, Shushikian requested changes
Переменные должны быть через var(), контейнеры должны быть едины для всех.
БЭМ должен использоваться верно

2022-04-03 10:32 UTC, Shushikian commented on src/partials/header-hero.html
> +    <div class="hero-container">
Используй единый контейнер, если надо менять настройки отображения контейнера, то используй @extend, либо добавлю тебе placeholder и будешь добавлять так "%placeholder__tab"

2022-04-03 10:32 UTC, Shushikian commented on src/sass/components/_btn.scss
> -    color: var(--btn-light-color);
Все пременные должны быть через var()

2022-04-03 10:32 UTC, Shushikian commented on src/sass/main.css
> +@charset "UTF-8";
Будут новые переменные, нужно будет обновить

2022-04-03 10:32 UTC, Shushikian commented on src/sass/util/_variables.scss
> -  --current-color-active-link:#D41443;
должны быть старые переменные

2022-04-03 10:35 UTC, Shushikian approved these changes
Исправил

2022-04-04 21:05 UTC, Shushikian commented
Устаревшие данные

2022-04-04 21:05 UTC, closed without merging